<?xml version="1.0" encoding="utf-8"?><Database Name="BDProyecto" Class="ModeloAhorrosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ahorro" Member="ahorro">
    <Type Name="ahorro">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="monto" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="progreso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fecha_creacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_limite" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.insertarAhorros" Method="insertarAhorros">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="monto" Type="System.Double" DbType="Float" />
    <Parameter Name="progreso" Type="System.Double" DbType="Float" />
    <Parameter Name="fecha_creacion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="fecha_limite" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarAhorros" Method="eliminarAhorros">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.buscarAhorros" Method="buscarAhorros">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="buscarAhorrosResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="monto" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="progreso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fecha_creacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_limite" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.actualizarAhorro" Method="actualizarAhorro">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="monto" Type="System.Double" DbType="Float" />
    <Parameter Name="progreso" Type="System.Double" DbType="Float" />
    <Parameter Name="fecha_limite" Type="System.DateTime" DbType="Date" />
    <Parameter Name="estado" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>